export const DATA_LOADED = 'DATA_LOADED';
export const CHECK_SEARCH = 'CHECK_SEARCH';
export const SORT_BY_COST = 'SORT_BY_COST';
export const SORT_BY_PUBLISHED_DATE = 'SORT_BY_PUBLISHED_DATE';
export const SHOW_RECENT_SEARCHES = 'SHOW_RECENT_SEARCHES';
export const APPLY_FILTER = 'APPLY_FILTER';
export const APPLY_COST_FILTER = 'APPLY_COST_FILTER';
